/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lthdt.chuong3.dohoa.frames;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import lthdt.chuong3.dohoa.coffeeLogic.CoffeeShop;
import lthdt.chuong3.dohoa.coffeeLogic.Manager;

/**
 *
 * @author thang
 */
public class Coffee extends javax.swing.JInternalFrame {

    Manager[] m;
    
    public Coffee() throws ParseException {
        initComponents();
        CoffeeShop[] a = new CoffeeShop[]{new CoffeeShop("Oke CF", "99 HĐH"),
        new CoffeeShop("Hi CF", "100 Phung Hung"), new CoffeeShop("D CF", "Hue")};
        
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
        m = new Manager[]{
            new Manager(a, 20000, "Thang", 1, df.parse("10-10-2001")),
            new Manager(new CoffeeShop[]{
                new CoffeeShop("Hue Thuong", "Nguyen Hue")
            }, 25000, "Nguyen Van B", 1, df.parse("01-12-2001"))
        };
        
        for (int i = 0; i<m.length;i++){
            CBNguoiQuanLy.addItem(m[i].getHoten());
        }
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        CBNguoiQuanLy = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShop = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setMaximizable(true);
        setTitle("Danh sách các quán Coffee");

        jLabel1.setText("Họ Tên Người Quản Lý");

        CBNguoiQuanLy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBNguoiQuanLyItemStateChanged(evt);
            }
        });

        tableShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên Quán", "Địa Chỉ"
            }
        ));
        jScrollPane1.setViewportView(tableShop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(CBNguoiQuanLy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBNguoiQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBNguoiQuanLyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBNguoiQuanLyItemStateChanged
        DefaultTableModel model = (DefaultTableModel) tableShop.getModel();
        int index = CBNguoiQuanLy.getSelectedIndex();
        model.setRowCount(0);
        
        CoffeeShop[] shops = m[index].getShops();
        for (int i = 0; i<m.length;i++){
             model.insertRow(model.getRowCount(), new Object[] {model.getRowCount()+1
                     ,shops[i].getName(), shops[i].getDiachi()});
        }
    }//GEN-LAST:event_CBNguoiQuanLyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBNguoiQuanLy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableShop;
    // End of variables declaration//GEN-END:variables
}
